# Site settings
title: Eenentwintig
author:
  name: Eenentwintig
  email: your-email@domain.com
description: "Bitcoin content - Bitcoin Only"

# Build settings
remote_theme: jekyll/minima

minima:
  skin: dark
  date_format: "%b %-d, %Y"